_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_delete: 0
  config_devel: 0
  contact: 0
  context: 0
  context_entity_field: 0
  context_ui: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dcc_common: 0
  dcc_general: 0
  dcc_migrations: 0
  dynamic_page_cache: 0
  editor: 0
  encrypt: 0
  entity_clone: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  google_tag: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  key: 0
  language: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  real_aes: 0
  redirect: 0
  search: 0
  sfweb2lead_webform: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  tfa: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  we_megamenu: 0
  webform: 0
  webform_attachment: 0
  webform_ui: 0
  trailing_slash: 1
  webform_bootstrap: 1
  xmlsitemap: 1
  views: 10
  paragraphs: 11
  field_states_ui: 200
  standard: 1000
theme:
  bootstrap4: 0
  dcc: 0
  claro: 0
  stable9: 0
profile: standard
