banner_title: 'Find out if you are eligible for a class action lawsuit'
banner_description: 'Take our FREE quiz to see if you qualify for a lawsuit.'
banner_button_link: 'https://evaluation.forthepeople.com/veteran_disability/getstarted/quiz'
banner_button_title: 'Begin Quiz'
