cloneable_entities:
  - block
  - block_content_type
  - block_content
  - comment
  - comment_type
  - contact_form
  - contact_message
  - context
  - editor
  - encryption_profile
  - field_config
  - field_storage_config
  - file
  - filter_format
  - google_tag_container
  - image_style
  - key_config_override
  - key
  - configurable_language
  - language_content_settings
  - media_type
  - media
  - menu_link_content
  - metatag_defaults
  - migration
  - migration_group
  - node
  - node_type
  - path_alias
  - redirect
  - search_page
  - shortcut_set
  - shortcut
  - action
  - menu
  - taxonomy_vocabulary
  - taxonomy_term
  - tour
  - user_role
  - user
  - webform_options
  - webform_submission
  - webform
  - xmlsitemap
  - view
  - paragraphs_type
  - paragraph
  - date_format
  - base_field_override
  - entity_view_mode
  - entity_form_display
  - entity_form_mode
  - entity_view_display
