_core:
  default_config_hash: SlH61T3fokeMgZ1EqsMR92gy7GIrwp1wo61_AerPqyo
enabled: true
paths: ''
enabled_entity_types: 'a:11:{s:13:"block_content";a:1:{s:5:"basic";i:0;}s:7:"comment";a:1:{s:7:"comment";i:0;}s:15:"contact_message";a:2:{s:8:"feedback";i:0;s:8:"personal";i:0;}s:4:"file";a:1:{s:4:"file";i:0;}s:5:"media";a:5:{s:5:"audio";i:0;s:8:"document";i:0;s:5:"image";i:0;s:12:"remote_video";i:0;s:5:"video";i:0;}s:17:"menu_link_content";a:1:{s:17:"menu_link_content";i:0;}s:4:"node";a:2:{s:7:"article";i:1;s:4:"page";i:1;}s:10:"path_alias";a:1:{s:10:"path_alias";i:1;}s:8:"shortcut";a:1:{s:7:"default";i:0;}s:13:"taxonomy_term";a:1:{s:4:"tags";i:0;}s:4:"user";a:1:{s:4:"user";i:0;}}'
